import { GridRowsProp } from "@mui/x-data-grid";

export const rows: GridRowsProp = [
    {
        id: 1,
        lastName: "Snow",
        firstName: "Jon",
        age: 35,
        status: "active",
    },
    {
        id: 2,
        lastName: "Lannister",
        firstName: "Cersei",
        age: 42,
        status: "inactive",
    },
    {
        id: 3,
        lastName: "Lannister",
        firstName: "Jaime",
        age: 45,
        status: "active",
    },
    {
        id: 4,
        lastName: "Stark",
        firstName: "Arya",
        age: 16,
        status: "active",
    },
    {
        id: 5,
        lastName: "Targaryen",
        firstName: "Daenerys",
        age: null,
        status: "inactive",
    },
    {
        id: 6,
        lastName: "Melisandre",
        firstName: null,
        age: 150,
        status: "active",
    },
    {
        id: 7,
        lastName: "Clifford",
        firstName: "Ferrara",
        age: 44,
        status: "inactive",
    },
    {
        id: 8,
        lastName: "Frances",
        firstName: "Rossini",
        age: 36,
        status: "active",
    },
    {
        id: 9,
        lastName: "Roxie",
        firstName: "Harvey",
        age: 65,
        status: "active",
    },
    {
        id: 10,
        lastName: "Stark",
        firstName: "Sansa",
        age: 21,
        status: "inactive",
    },
    {
        id: 11,
        lastName: "Bolton",
        firstName: "Ramsay",
        age: 30,
        status: "inactive",
    },
    {
        id: 12,
        lastName: "Baelish",
        firstName: "Petyr",
        age: 40,
        status: "active",
    },
    {
        id: 13,
        lastName: "Greyjoy",
        firstName: "Theon",
        age: 25,
        status: "inactive",
    },
    {
        id: 14,
        lastName: "Mormont",
        firstName: "Jorah",
        age: 50,
        status: "active",
    },
    {
        id: 15,
        lastName: "Tyrell",
        firstName: "Margaery",
        age: 28,
        status: "inactive",
    },
    {
        id: 16,
        lastName: "Baratheon",
        firstName: "Stannis",
        age: 38,
        status: "inactive",
    },
    {
        id: 17,
        lastName: "Seaworth",
        firstName: "Davos",
        age: 55,
        status: "active",
    },
    {
        id: 18,
        lastName: "Clegane",
        firstName: "Sandor",
        age: 42,
        status: "active",
    },
    {
        id: 19,
        lastName: "Tarth",
        firstName: "Brienne",
        age: 32,
        status: "active",
    },
    {
        id: 20,
        lastName: "Giantsbane",
        firstName: "Tormund",
        age: 38,
        status: "active",
    },
    {
        id: 21,
        lastName: "Reed",
        firstName: "Howland",
        age: 60,
        status: "inactive",
    },
    {
        id: 22,
        lastName: "Tarly",
        firstName: "Samwell",
        age: 26,
        status: "active",
    },
    {
        id: 23,
        lastName: "Tarly",
        firstName: "Randyll",
        age: 58,
        status: "inactive",
    },
    {
        id: 24,
        lastName: "Gilly",
        firstName: null,
        age: 22,
        status: "active",
    },
    {
        id: 25,
        lastName: "Tanner",
        firstName: "Lollys",
        age: 30,
        status: "inactive",
    },
    {
        id: 26,
        lastName: "Slynt",
        firstName: "Janos",
        age: 50,
        status: "inactive",
    },
    {
        id: 27,
        lastName: "Thorne",
        firstName: "Alliser",
        age: 55,
        status: "inactive",
    },
    {
        id: 28,
        lastName: "Umber",
        firstName: "Smalljon",
        age: 35,
        status: "inactive",
    },
    {
        id: 29,
        lastName: "Karstark",
        firstName: "Harald",
        age: 40,
        status: "inactive",
    },
    {
        id: 30,
        lastName: "Mormont",
        firstName: "Lyanna",
        age: 12,
        status: "active",
    },
    {
        id: 31,
        lastName: "Glover",
        firstName: "Robett",
        age: 45,
        status: "inactive",
    },
    {
        id: 32,
        lastName: "Cerwyn",
        firstName: "Cley",
        age: 18,
        status: "inactive",
    },
    {
        id: 33,
        lastName: "Manderly",
        firstName: "Wyman",
        age: 60,
        status: "active",
    },
    {
        id: 34,
        lastName: "Hornwood",
        firstName: "Halys",
        age: 50,
        status: "inactive",
    },
    {
        id: 35,
        lastName: "Tallhart",
        firstName: "Leobald",
        age: 42,
        status: "inactive",
    },
    {
        id: 36,
        lastName: "Ryswell",
        firstName: "Rodrik",
        age: 48,
        status: "inactive",
    },
    {
        id: 37,
        lastName: "Dustin",
        firstName: "Barbrey",
        age: 40,
        status: "active",
    },
    {
        id: 38,
        lastName: "Flint",
        firstName: "Robin",
        age: 30,
        status: "active",
    },
    {
        id: 39,
        lastName: "Norrey",
        firstName: "Brandon",
        age: 28,
        status: "active",
    },
    {
        id: 40,
        lastName: "Wull",
        firstName: "Hugo",
        age: 55,
        status: "active",
    },
    {
        id: 41,
        lastName: "Liddle",
        firstName: "Morgan",
        age: 38,
        status: "active",
    },
    {
        id: 42,
        lastName: "Knott",
        firstName: "Theo",
        age: 32,
        status: "active",
    },
    {
        id: 43,
        lastName: "Harclay",
        firstName: "Rickard",
        age: 45,
        status: "inactive",
    },
    {
        id: 44,
        lastName: "Marsh",
        firstName: "Bowen",
        age: 50,
        status: "active",
    },
    {
        id: 45,
        lastName: "Yarwyck",
        firstName: "Othell",
        age: 55,
        status: "active",
    },
    {
        id: 46,
        lastName: "Locke",
        firstName: null,
        age: 40,
        status: "inactive",
    },
    {
        id: 47,
        lastName: "Cassel",
        firstName: "Rodrik",
        age: 60,
        status: "inactive",
    },
    {
        id: 48,
        lastName: "Poole",
        firstName: "Vayon",
        age: 50,
        status: "inactive",
    },
    {
        id: 49,
        lastName: "Poole",
        firstName: "Jeyne",
        age: 18,
        status: "active",
    },
    {
        id: 50,
        lastName: "Cassel",
        firstName: "Beth",
        age: 22,
        status: "active",
    },
    {
        id: 51,
        lastName: "Mazin",
        firstName: "Roose",
        age: 38,
        status: "inactive",
    },
    {
        id: 52,
        lastName: "Ryder",
        firstName: "Rickard",
        age: 27,
        status: "active",
    },
    {
        id: 53,
        lastName: "Mollen",
        firstName: "Helman",
        age: 45,
        status: "active",
    },
    {
        id: 54,
        lastName: "Whitehill",
        firstName: "Ludd",
        age: 50,
        status: "inactive",
    },
    {
        id: 55,
        lastName: "Forrester",
        firstName: "Gregor",
        age: 48,
        status: "inactive",
    },
    {
        id: 56,
        lastName: "Glenmore",
        firstName: "Elaena",
        age: 22,
        status: "active",
    },
    {
        id: 57,
        lastName: "Branfield",
        firstName: "Elissa",
        age: 35,
        status: "active",
    },
    {
        id: 58,
        lastName: "Tuttle",
        firstName: "Andros",
        age: 40,
        status: "inactive",
    },
    {
        id: 59,
        lastName: "Ashford",
        firstName: "Quentyn",
        age: 28,
        status: "active",
    },
    {
        id: 60,
        lastName: "Peasebury",
        firstName: "Tristan",
        age: 33,
        status: "active",
    },
    {
        id: 61,
        lastName: "Wylde",
        firstName: "Casper",
        age: 45,
        status: "inactive",
    },
    {
        id: 62,
        lastName: "Staedmon",
        firstName: "Alesander",
        age: 50,
        status: "active",
    },
    {
        id: 63,
        lastName: "Errol",
        firstName: "Sebastian",
        age: 38,
        status: "active",
    },
    {
        id: 64,
        lastName: "Estermont",
        firstName: "Aemon",
        age: 42,
        status: "inactive",
    },
    {
        id: 65,
        lastName: "Mertyns",
        firstName: "Endrew",
        age: 55,
        status: "active",
    },
    {
        id: 66,
        lastName: "Penrose",
        firstName: "Cortnay",
        age: 48,
        status: "inactive",
    },
    {
        id: 67,
        lastName: "Musgood",
        firstName: "Lester",
        age: 30,
        status: "active",
    },
    {
        id: 68,
        lastName: "Peake",
        firstName: "Laswell",
        age: 35,
        status: "inactive",
    },
    {
        id: 69,
        lastName: "Shermer",
        firstName: "Garth",
        age: 40,
        status: "active",
    },
    {
        id: 70,
        lastName: "Hastwyck",
        firstName: "Bonifer",
        age: 60,
        status: "inactive",
    },
    {
        id: 71,
        lastName: "Fell",
        firstName: "Harlan",
        age: 32,
        status: "active",
    },
    {
        id: 72,
        lastName: "Bolling",
        firstName: "Boremund",
        age: 27,
        status: "active",
    },
    {
        id: 73,
        lastName: "Buckler",
        firstName: "Ralph",
        age: 45,
        status: "inactive",
    },
    {
        id: 74,
        lastName: "Cafferen",
        firstName: "Barristan",
        age: 50,
        status: "active",
    },
    {
        id: 75,
        lastName: "Caron",
        firstName: "Bryce",
        age: 38,
        status: "inactive",
    },
    {
        id: 76,
        lastName: "Dondarrion",
        firstName: "Manfred",
        age: 42,
        status: "active",
    },
    {
        id: 77,
        lastName: "Foote",
        firstName: "Philip",
        age: 55,
        status: "active",
    },
    {
        id: 78,
        lastName: "Gower",
        firstName: "Garse",
        age: 48,
        status: "inactive",
    },
    {
        id: 79,
        lastName: "Grandison",
        firstName: "Narbert",
        age: 30,
        status: "active",
    },
    {
        id: 80,
        lastName: "Morrigen",
        firstName: "Guyard",
        age: 35,
        status: "inactive",
    },
    {
        id: 81,
        lastName: "Swann",
        firstName: "Gulian",
        age: 40,
        status: "active",
    },
    {
        id: 82,
        lastName: "Selmy",
        firstName: "Arstan",
        age: 60,
        status: "inactive",
    },
    {
        id: 83,
        lastName: "Tarly",
        firstName: "Dickon",
        age: 32,
        status: "active",
    },
    {
        id: 84,
        lastName: "Hightower",
        firstName: "Baelor",
        age: 27,
        status: "active",
    },
    {
        id: 85,
        lastName: "Oakheart",
        firstName: "Arys",
        age: 45,
        status: "inactive",
    },
    {
        id: 86,
        lastName: "Rowan",
        firstName: "Mathis",
        age: 50,
        status: "active",
    },
    {
        id: 87,
        lastName: "Tarly",
        firstName: "Samwell",
        age: 38,
        status: "inactive",
    },
    {
        id: 88,
        lastName: "Hunt",
        firstName: "Hyle",
        age: 42,
        status: "active",
    },
    {
        id: 89,
        lastName: "Ambrose",
        firstName: "Arthur",
        age: 55,
        status: "active",
    },
    {
        id: 90,
        lastName: "Blackbar",
        firstName: "Brus",
        age: 48,
        status: "inactive",
    },
    {
        id: 91,
        lastName: "Cuy",
        firstName: "Emmon",
        age: 30,
        status: "active",
    },
    {
        id: 92,
        lastName: "Mullendore",
        firstName: "Martyn",
        age: 35,
        status: "inactive",
    },
    {
        id: 93,
        lastName: "Serry",
        firstName: "Osbert",
        age: 40,
        status: "active",
    },
    {
        id: 94,
        lastName: "Willum",
        firstName: "Parmen",
        age: 60,
        status: "inactive",
    },
    {
        id: 95,
        lastName: "Bridges",
        firstName: "Theo",
        age: 32,
        status: "active",
    },
    {
        id: 96,
        lastName: "Bushy",
        firstName: "Will",
        age: 27,
        status: "active",
    },
    {
        id: 97,
        lastName: "Caswell",
        firstName: "Lorent",
        age: 45,
        status: "inactive",
    },
    {
        id: 98,
        lastName: "Hightower",
        firstName: "Gerold",
        age: 55,
        status: "inactive",
    },
    {
        id: 99,
        lastName: "Dayne",
        firstName: "Arthur",
        age: 30,
        status: "inactive",
    },
    {
        id: 100,
        lastName: "Whent",
        firstName: "Oswell",
        age: 40,
        status: "inactive",
    },
];
